# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('blood_group', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
                ('rh', models.CharField(max_length=20)),
                ('diseases', models.TextField()),
                ('pass_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
