# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='blood_group',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1),
        ),
        migrations.AlterField(
            model_name='donor',
            name='rh',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1),
        ),
    ]
